### PR TITLE
install: A flag to block installing rpi2only apps on rpi1

### PR DESCRIPTION
**Pull request by pazdera**
Related to: https://github.com/KanoComputing/peldins/issues/1747

### CODE REVIEW

**Comment by pazdera** [comment]
cc @alex5imon

**Comment by alex5imon** [comment]
Please merge :+1:

**Comment by Ealdwulf** [comment]
@pazdera, Does this prevent the apps being shown in the list, or  object
when users try to download them? Because that might be a bit irritating.

**Comment by pazdera** [comment]
@Ealdwulf That would have to happen on Kano World (that's where the list is) as we discussed this morning during scrum.

I guess that is a decision to make whether we want to hide them completely or at least mark them incompatible (as a motivation for people to upgrade to Pi2). In any case, there aren't any rpi2 specific apps yet, so we have plenty of time to figure it out :-).

**Pull request merged**
